# Generated by Django 2.2.14 on 2022-08-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Z', 'Zapatos'), ('B', 'Botas'), ('NZ', 'Zapatos Niños')], max_length=2),
        ),
    ]
